services:

  db:
    image: postgres:18-alpine
    container_name: tasks_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pgPaSSwOrD"
      POSTGRES_DB: "tasks"
    ports:
      - "5432:5432"
    volumes:
      - db_postgres:/var/lib/postgresql/data
    networks:
      - tasks_app_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: tasks_db_pgadmin
    ports:
      - "8081:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/root/.pgadmin
    networks:
      - tasks_app_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  python:
    image: tasks_app:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tasks_app
    restart: unless-stopped
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pgPaSSwOrD"
      POSTGRES_DB: "tasks"
      POSTGRES_PORT: "5432"
    ports:
      - "8080:8080"
    networks:
      - tasks_app_network
    depends_on:
      db:
        condition: service_healthy

networks:
  tasks_app_network:
    driver: bridge

volumes:
  db_postgres:
  pgadmin_data:
